#This workflow will deploy the app on the ORACLECloud compute VM

name: Deploy Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: 152.67.6.16
        username: assassino
        key: ${{ secrets.ID_RSA_COMMON }}
        passphrase: ${{ secrets.ID_RSA_COMMON_PASSPHRASE }}
        script: sh Archives/Combined-Mathematics/etc/deploy.sh
